### PR TITLE
fastify fix and package update

### PR DESCRIPTION
**Pull request by ReuschelCGN**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jfberry** [comment]
Want to merge (I know fastify is right) - only concern was the reported performance difference with one or other of the components

**Comment by kbtbc** [comment]
I think my performance issue was a fluke with pm2 and my cache during initial test.  Testing this again for the last hour now seems solid.  I'm not using the api, but fastify errors are gone 😝

**Comment by jfberry** [comment]
node config -> 3.3.10 - should resolve the node 20, 22 issue (we can test these afterwards)

**Comment by jfberry** [comment]
I have merged develop to master, so please uplift to poracle v4.8.0

**Pull request merged**
