### PR TITLE
Fix JSON parsing in koji.js

### LINKED ISSUE #827: Koji config is not readable from docker
https://github.com/KartulUdus/PoracleJS/blob/9224242e06befb4e0aa0c369683a1355ee336edf/src/util/koji.js#L17

If I remove that check manually bearer token can be read from config. No ugly json, can be parsed successfully without that check.

### PR DESCRIPTION
**Pull request by Fabio1988**
## Description
It can happen that JSON files have a special encoding character at the beginning, this check would prevent loading the json. we already use try/catch here

## Motivation and Context

I want to use Koji with Poracle (both in docker)
fixes #827 

## How Has This Been Tested?

Bearer token is now detected after that change

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jfberry** [comment]
Really this shouldn't be happening here at all but rather in the load geofence where proper config loader has already been called

**Comment by TurtIeSocks** [comment]
I'm fine to bring this process internally, but I would need help with it as I couldn't get it to work nicely with the rest of the codebase.

**Review by TurtIeSocks — APPROVED** [review]

**Comment by Fabio1988** [comment]
@jfberry could we merge that fix until we find a better solution pls? :)

**Comment by jfberry** [comment]
The fix you have taken out was introduced because it was crashing

**Comment by Fabio1988** [comment]
> The fix you have taken out was introduced because it was crashing

weird it's not crashing for me with that change. so we have several cases. and we definitely have to fix/rework the way how we use koji

**Comment by Fabio1988** [comment]
reopen the ticket again

**Pull request closed without merging**
