### PR TITLE
Special case tracking pokemon 'everything' instead of having individual entries for each mon

### PR DESCRIPTION
**Pull request by jfberry**
## Description
The existing implementation for !track everything adds a database entry for every single pokemon. This is inefficient and results in a massive !tracked report. This change allows a '0' to be entered under the pokemon id representing all pokemon.
It does not require a database change as the old format still works. If a user does !untrack everything it will still remove the old entries so the database will gradually move to the new format

## How Has This Been Tested?

Tested locally, would appreciate feedback

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Piikachuu** [comment]
Hi thank for this pr , but i have issue with this :/ 
when i track everyhting on log i dont have list of mon tracked and on db i have only 1 row empty so nothing is sended..

log poracle:
image

db:
image

!tracked result
image

**Comment by jfberry** [comment]
The point is that everything is now a single row in the database with pokemon_id = 0
You can see that the query change in monster.js will now pick this and match against all pokemon.
So it should be the case that there is one row but the alerts should still function.

Have you found an alert that you have missed?

**Comment by Piikachuu** [comment]
its ok all is fine after multi tests ;)

**Comment by jfberry** [comment]
Updated to special case 'gen' - eg !track everything gen1 will put the individual mon in the database rather than falling back to the everything special case

**Comment by kamieniarz** [comment]
This PR increased my CPU usage by a lot so sth is wrong with it in my case

**Comment by jfberry** [comment]
Interesting. If you are sure it is this PR then hit me up on discord and we can work through it - the only thing it could be is the modification of the query (to check for =0 as well as a mon). Are you mysql or sqlite? Is mysql on the same box? Is it mysql which is hogging the CPU?

**Pull request merged**
