### PR TITLE
Resolve Issue #112

### PR DESCRIPTION
**Pull request by nakratz**
This resolves the reported Issue of #112

## Description

Resolves Reported Egg notification on #112 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by KartulUdus** [comment]
how does rounding your distance to the alert fix egg alerts 🤔

**Comment by nakratz** [comment]
Was looking at how the raids were being reported and compared SQL queries. Raid had the round in and egg who cares didn't. 🤷🏻‍♂️

**Comment by KartulUdus** [comment]
but does it resolve the issue for you like the title suggests? 😄

**Comment by nakratz** [comment]
Indeed it did. Looking at all of the other controllers for pokestops, Pokemon, and quests and raid they all include round in that distance query.

**Comment by KartulUdus** [comment]
what database do you use?

**Comment by nakratz** [comment]
Server version: 10.3.11-MariaDB-1:10.3.11+maria~bionic-log - mariadb.org binary distribution

**Pull request merged**
