### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by fosJoddie**
Update non-breaking packages to latest version

This excludes packages that have transfered to ESModule format and Discordjs which has breaking changes in the latest version

## Description
Updates all packages that have newer versions that do not break the current code.

## Motivation and Context
A step towards removing `npm audit` warnings and minimize the version gap for the dependencies.

## How Has This Been Tested?
Currently running on my test system

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Dependency Update

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jfberry** [comment]
Axios is potentially breaking so I didn’t get time to test yet - are you running 1.x ok?

**Comment by jfberry** [comment]
Please can pr be against develop branch

**Comment by fosJoddie** [comment]
> Please can pr be against develop branch

flip. I swear I triple checked this. Lemme just push the change again to fix the conflict as well

**Comment by fosJoddie** [comment]
> axios bad!?

Yeah, I need to look up where we use axios and double check it

**Comment by fosJoddie** [comment]
PR ready to be tested,

> Axios is potentially breaking so I didn’t get time to test yet - are you running 1.x ok?

Axios still worked for me on the one thing I use, but I'll try and find the docs to look for breaking changes if you like

**Pull request merged**
