### PR TITLE
fix Steel Grunt Typs - also for translations

### PR DESCRIPTION
**Pull request by ReuschelCGN**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jfberry** [comment]
You can't change this here. It has to be upstream. @TurtIeSocks

**Comment by jfberry** [comment]
Ah, this is deliberately against master? Or accidentally?

**Comment by TurtIeSocks** [comment]
> You can't change this here. It has to be upstream. @TurtIeSocks 
> 

?

**Comment by jfberry** [comment]
> > You can't change this here. It has to be upstream. @TurtIeSocks
> 
> ?

This is a change to grunts.json - but it's against master. So I am doubly confused, I am sure @ReuschelCGN will be along to explain to us both soon :-)

**Comment by Fabio1988** [comment]
There is no "Metal" type in pokemon?! it's called steel :) 

https://bulbapedia.bulbagarden.net/wiki/Steel_(type)

**Comment by jfberry** [comment]
Right, but this is a change to master and you guys are on develop? Is this just being proactive and it is ok on master?

**Comment by Fabio1988** [comment]
ahh I see... you meatn master branch..... I think it should be pointed to `develop`

**Comment by jfberry** [comment]
Except that on develop, this is generated by `npm run generate` and if the generation is wrong then it's a problem with the generator code (or potentially the data source, which is malte's grunt repository I think)

**Comment by ReuschelCGN** [comment]
I commit it here, because i thinked that poracleweb picked it up from there... but that is outdated
the information come from:
https://raw.githubusercontent.com/WatWowMap/Masterfile-Generator/master/master-latest-poracle.json
will close it here

**Comment by jfberry** [comment]
https://github.com/WatWowMap/Masterfile-Generator
This is the repository we pull from (which is why I mentioned @TurtIeSocks earlier)
Looking at the poracle masterfile, it has "metal" type in the grunts section so you could raise an issue there (or Turtle may chip in here)

**Pull request closed without merging**
