### PR TITLE
Add support for more Telegram parse modes

### PR DESCRIPTION
**Pull request by Kinrre**
## Description
Telegram notifications support three different parse modes, MarkdownV2, HTML and Markdown (legacy) https://core.telegram.org/bots/api#markdownv2-style.

PoracleJS hardcodes the usage of the legacy mode, but it presents a problem, for example, it can not be underlined text in the notifications, so I have added that the user can use the parse mode it would like.

*Note:* MarkdownV2 requires lot of escaped characters like the dot '.', so its a problem for not rounded IVs.

## How Has This Been Tested?

HTML and Markdown works perfectly, MarkdownV2 has its problems as it is stated before.

I also updated the default DTS to specify the parse mode, so the users can know that this support has been included.

## Screenshots (if appropriate):
Example of underlined and italic text using the HTML parse mode.
html_telegram

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jfberry** [comment]
Perhaps could regularise the setting to make sure it isn't one that the api is going to choke on
eg

```javascript
let parse_mode = 'Markdown'
switch((data.message.parse_mode ?? 'markdown').toLowerCase()) {
  case 'markdownv2': { 
    parse_mode = 'MarkdownV2';
    break;
  }
  case 'html': {
     parse_mode = 'HTML'
     break
   }
  default : 
     break
}

```

**Comment by Kinrre** [comment]
I have been testing your suggestion and the parse mode for the API is case insensitive, so it is not needed to make that change no?

**Comment by jfberry** [comment]
> I have been testing your suggestion and the parse mode for the API is case insensitive, so it is not needed to make that change no?

I didn't realise that, but in any case this restricts to supported types rather than having an error so still useful?

**Comment by Kinrre** [comment]
Yeah, you are right, I haven't thought about that. I just added the part of code that restrict to supported types.

**Comment by jfberry** [comment]
If this is all tested then and you are happy I will merge :-)

**Comment by Kinrre** [comment]
Yeah, all good from my side (HTML + Markdown)! 😄 

MarkdownV2 has its problems as stated in the first message, but with HTML you can do everything legacy Markdown doesn't support.

**Comment by jfberry** [comment]
I think HTML matches poracle's handlebars capability better anyway, escaping happens automatically for & etc with {{ }}

**Pull request merged**
