### PR TITLE
Include Raid/Egg Mega (6) on args "everything" V4

### PR DESCRIPTION
**Pull request by Piikachuu**
## Description
Add Raid/Egg Mega (6) with commands !raid/egg everything

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Pogodenhelder** [comment]
i think beside your egg level6 added you also have added an old pr about rarity into this pr. Oo

**Comment by Piikachuu** [comment]
again ? shit :@

**Comment by jfberry** [comment]
> again ? shit :@

Yes - I think this would be a no-brainer PR without this; will you fix or would you like me to do an alternative PR?

**Comment by Piikachuu** [comment]
I don't know how to use PR very well. I will try to create another branch but I promise nothing 😞 But if you want propose another PR its ok ;)

**Comment by jfberry** [comment]
> I don't know how to use PR very well. I will try to create another branch but I promise nothing 😞 But if you want propose another PR its ok ;)

All you do is commit a further change to the branch undoing the rarity and the PR will be updated.

**Comment by jfberry** [comment]
Applied by hand

**Pull request closed without merging**
