### PR TITLE
Added option to track when a gym is being attacked

### PR DESCRIPTION
**Pull request by Lecnets**
- Adds option to track when a gym is being attacked

## How Has This Been Tested?
When the gym is under attack

```json
{ gym_id: '123456', latitude: 0, longitude: 0, team_id: 1, name: "Gym", slots_available: 0, is_ar_scan_eligible: 0, is_in_battle: 1, description: "Gym Description", url: 'http://lh3.googleusercontent.com/gymImg', is_ex_raid_eligible: 0, old_team_id: 1, old_slots_available: 0, last_owner_id: 1, googleMapUrl: 'https://www.google.com/maps/search/?api=1&query=0,0', appleMapUrl: 'https://maps.apple.com/maps?daddr=0,0', wazeMapUrl: 'https://www.waze.com/ul?ll=0,0&navigate=yes&zoom=17', gymName: "Gym", gymUrl: 'http://lh3.googleusercontent.com/gymImg', tth: { days: 0, hours: 1, minutes: 0, seconds: 0 }, applemap: 'https://maps.apple.com/maps?daddr=0,0', mapurl: 'https://www.google.com/maps/search/?api=1&query=0,0', distime: undefined, matchedAreas: [ { name: 'testarea', description: undefined, displayInMatches: true, group: undefined } ], matched: [ 'testarea' ], gymId: '123456', teamId: 1, oldTeamId: 1, previousControlId: 1, teamNameEng: 'Mystic', oldTeamNameEng: 'Mystic', previousControlNameEng: 'Mystic', gymColor: '3B4CCA', slotsAvailable: 0, oldSlotsAvailable: 0, ex: false, color: '3B4CCA', isInBattle: 1 }
```

After stopping the attack in the gym

```json
{ gym_id: '123456', latitude: 0, longitude: 0, team_id: 1, name: "Gym", slots_available: 0, is_ar_scan_eligible: 0, is_in_battle: 0, description: "Gym Description", url: 'http://lh3.googleusercontent.com/gymImg', is_ex_raid_eligible: 0, old_team_id: 1, old_slots_available: 0, last_owner_id: 1, googleMapUrl: 'https://www.google.com/maps/search/?api=1&query=0,0', appleMapUrl: 'https://maps.apple.com/maps?daddr=0,0', wazeMapUrl: 'https://www.waze.com/ul?ll=0,0&navigate=yes&zoom=17', gymName: "Gym", gymUrl: 'http://lh3.googleusercontent.com/gymImg', tth: { days: 0, hours: 1, minutes: 0, seconds: 0 }, applemap: 'https://maps.apple.com/maps?daddr=0,0', mapurl: 'https://www.google.com/maps/search/?api=1&query=0,0', distime: undefined, matchedAreas: [ { name: 'testarea', description: undefined, displayInMatches: true, group: undefined } ], matched: [ 'testarea' ], gymId: '123456', teamId: 1, oldTeamId: 1, previousControlId: 1, teamNameEng: 'Mystic', oldTeamNameEng: 'Mystic', previousControlNameEng: 'Mystic', gymColor: '3B4CCA', slotsAvailable: 0, oldSlotsAvailable: 0, ex: false, color: '3B4CCA', isInBattle: 0 }
```

## Screenshots (if appropriate):
testGym

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jfberry** [comment]
This is a contentious feature; certainly will not merge without it being optional (and defaulting to off). But equally it has been asked for a few times and @Lecnets has gone to the effort of building it so I will support him/her in getting the feature right and would plan to merge when it is

**Comment by kamieniarz** [comment]
I'm testing it right now and it works. One thing that could be improved somehow - this tracking option can be very spammy especially when full gym is going down. Any option to prevent spam would be great tho. Maybe 1 battle_changes notification per x minutes? Sth like `!gym everything d100 battle_changes5` where 5 is 5min cooldown between next notification?

**Comment by TurtIeSocks** [comment]
@jfberry what's the planned poracle version for this one? I'll integrate the version check starting when I add support for this on ReactMap side.

**Comment by jfberry** [comment]
> @jfberry what's the planned poracle version for this one? I'll integrate the version check starting when I add support for this on ReactMap side.

Still a few kinks to work out, but I would say it's likely to be 4.3.2

**Comment by TurtIeSocks** [comment]
https://github.com/WatWowMap/ReactMap/pull/249

Untested, but ready when you guys are :)

**Comment by kamieniarz** [comment]
I've been testing this PR and I have 2 remarks:
1. After every "in battle" notification I'm getting info about team change, which is not true. It doesn't matter if number of sloots changes or anything like that = it just happens every single time
2. As I mentioned before - "in battle" is very spammy. I can get like 20 notifications in few mins when full gym is beeing taken down. This is unnecessary. One notification on first battle should be enough.

**Comment by jfberry** [comment]
> I've been testing this PR and I have 2 remarks:
> 
> 1. After almost every "in battle" notification I'm getting info about team change, which is not true. It doesn't matter if number of sloots changes or anything like that = it just happens every single time

Can you DM me a sequence? Do you have the webhooks that generated this? For the PR to be qualified as working correctly I think it needs to post about in_battle, but then be quiet about battle changes for a period of time (as this will toggled) but still report any slot reduction or colour changes of course!

> 2. As I mentioned before - "in battle" is very spammy. I can get like 20 notifications in few mins when full gym is beeing taken down. This is unnecessary. One notification on first battle should be enough.

I have proposed a way to squash the alerting after the initial 'in battle' so only subsequent slot or colour changes would come through

**Comment by Lecnets** [comment]
> I'm testing it right now and it works. One thing that could be improved somehow - this tracking option can be very spammy especially when full gym is going down. Any option to prevent spam would be great tho. Maybe 1 battle_changes notification per x minutes? Sth like `!gym everything d100 battle_changes5` where 5 is 5min cooldown between next notification?

At the moment I think there is no need to create the option to change the cooldown (currently it is 5min, and it can renew if the RDM/MAD resend the in_battle as true again). If that's really needed, I can add the cooldown change option as a new feature.

**Pull request merged**
