### PR TITLE
fix: fort update webhook

### PR DESCRIPTION
**Pull request by TurtIeSocks**
## Description

- Removes old references to c&p'd nest code
- Sets `time` to current time

## Motivation and Context

Valid time and fix c&p bugs

## How Has This Been Tested?

Currently untested 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ReuschelCGN** [comment]
https://github.com/TurtIeSocks/PoracleJS/blob/f07c85725db0645ca78b9aed8592e6dc756cc14e/src/controllers/fortupdate.js#L208

think this could also be remove

**Comment by ReuschelCGN** [comment]
removing Line: 100 makes probs with Lines: 255-258

**Comment by jfberry** [comment]
Removing tth will cause the senders to fail if clean specified at very least

**Comment by Fabio1988** [comment]
Should we even allow to `clean` those hooks? Imo this does not make sense, right?

**Comment by jfberry** [comment]
> Should we even allow to `clean` those hooks? Imo this does not make sense, right?

Even if you don't allow clean in the track command the tth values need to be there for the sending code not to crash

**Pull request merged**
