### PR TITLE
translation for new "battle_changes" command

### PR DESCRIPTION
**Pull request by ReuschelCGN**
!gym everything d100 battle_changes5 - where 5 is 5min cooldown between next notification

### CODE REVIEW

**Comment by Fabio1988** [comment]
this would mean for german the command is `!arena alle wird_angegriffen` ? :)

**Comment by TurtIeSocks** [comment]
Is battle_changes5 a thing? 🤔

**Comment by jfberry** [comment]
No it isn’t

—
James Berry, m. 07768 021031


________________________________

**Comment by jfberry** [comment]
Can this be merged anyway though? I think the translation is unaffected by this misunderstanding

**Comment by Fabio1988** [comment]
I'm not sure about translation itself. It's said "is in battle" in english. It's difficult to translate "battle_changes" in german... `unter_angriff`, `umkämpft`, `Kampfänderung`

**Pull request merged**
