### PR TITLE
V3 forms json

### PR DESCRIPTION
**Pull request by philcerf**

### CODE REVIEW

**Comment by muckelba** [comment]
FFS, why are you updating V3 and not switching to V4? :D

**Comment by gcm-explo1t** [comment]
BC v3 has full telegram support :)

**Comment by muckelba** [comment]
So does  https://github.com/BoxService/PoracleJS or https://github.com/KartulUdus/PoracleJS/pull/246

**Comment by jfberry** [comment]
v4 PR246 adds telegram support, and I would consider it stable now (I know half a dozen people running it at least). And support for telegram in PoracleWeb too!

**Comment by philcerf** [comment]
> FFS, why are you updating V3 and not switching to V4? :D

as @gcm-explo1t said... we still have to use it because of TG support... and AFAICs you directly use the same format than RocketMAD in dev anyway?

**Comment by gcm-explo1t** [comment]
> 
> 
> So does https://github.com/BoxService/PoracleJS or #246

So i did not even know about this repo, as it is not linked anywhere near MAD and the pr is 7 days old not merged and has no comments about working or not. So sry that we try to keep v3 working as long as we can to keep poracle on telegram alive :)

**Comment by jfberry** [comment]
I wrote the v4 telegram PR, it’s good but take your time. Come and join us on the discord

**Comment by muckelba** [comment]
It got announced in the Poracle Discord ¯\_(ツ)_/¯. The PR title says that its feature complete and @jfberry asked for testers in the Discord as well, but i'll not stop you from developing stuff. Just wanted to make sure that you dont waste your time.

**Comment by gcm-explo1t** [comment]
> 
> 
> I wrote the v4 telegram PR, it’s good but take your time. Come and join us on the discord

If i get time this week i'll try it out :)

**Comment by gcm-explo1t** [comment]
Currently testing the https://github.com/KartulUdus/PoracleJS/pull/246 however some pkm are missing?

**Comment by philcerf** [comment]
@gcm-explo1t let's perhaps keep discussion about the TG support in V4, at the PR there :-)

**Comment by philcerf** [comment]
FYI: From my side, we could close this without merging, since we've now migrated to the devel branch… Though it might be interesting for others still on v3.

**Pull request closed without merging**
