### PR TITLE
Localisation de for default dts

### PR DESCRIPTION
**Pull request by hamster007Github**
Adding/extend german localisation

## Description
Added german templates to default dts.json
Extend german localisation file de.json based on fr.json (without quest parts)
Remark: Someone with Discord should test "de" DTS templates for discord.

## Motivation and Context
German support missing for DTS and many phrases in localisation file

## How Has This Been Tested?
local setup with pokemon tracking+ weather change on Telegram. Rest untested.

## Screenshots (if appropriate):
-

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jfberry** [comment]
See #324 please work out between yourselves which PR will be master as I want to merge one

**Comment by philcerf** [comment]
@hamster007Github 🤣 great timing

We can obviously take your dts.json, but TBH (no ofense meant) it seems my de.json is more correct...
- command names should IMO be in lower case
- several of your translations (like nebelig, bewölkt) don't use the official names from the game master
- "Incense Ordinary":"Sternenstück", "Blaue Schleife" or "Regnerisch" (for Castforms Rainy form) are just wrong
- Poffin is Knursp in German

**Comment by philcerf** [comment]
Perhaps it's best if you diff mine with yours and tell me whether there are any individual points which you'd prefer of either yours or mine.

**Comment by hamster007Github** [comment]
> @hamster007Github 🤣 great timing
> 
> We can obviously take your dts.json, but TBH (no ofense meant) it seems my de.json is more correct...
> 
> * command names should IMO be in lower case
> * several of your translations (like nebelig, bewölkt) don't use the official names from the game master
> * "Incense Ordinary":"Sternenstück", "Blaue Schleife" or "Regnerisch" (for Castforms Rainy form) are just wrong
> * Poffin is Knursp in German
I'm fine to use your PR. Just provide mine to have more then "nothing" 😁 Please integrate my DTS or your own so we have also german DTS support.
@jfberry you can close this PR

**Comment by philcerf** [comment]
@hamster007Github Can't you simply remove commit 9c2fa44 from your PR... then you'd get proper credit as commit author and James can merge your changes to dts.json, and take the locale from my PR, once it's fully finished (should be later the day).

**Comment by hamster007Github** [comment]
> @hamster007Github Can't you simply remove commit [9c2fa44](https://github.com/KartulUdus/PoracleJS/commit/9c2fa44e621046390338a6c6cee29fa8d42523ae) from your PR... then you'd get proper credit as commit author and James can merge your changes to dts.json, and take the locale from my PR, once it's fully finished (should be later the day).

Also a good idea. I'm a absolut git noob and have to carry out first, how to do this 😁 First try was wrong... I will give it a new try later this day.

**Comment by hamster007Github** [comment]
Removed de.json file so only dts.json remaining. So, no more conflict with #324

**Comment by philcerf** [comment]
I think that made it worse ;-) now you have 5 commits in the PR.

That should work:
https://stackoverflow.com/questions/1338728/delete-commits-from-a-branch-in-git

So either:
git reset --hard HEAD~1
and go back one by one, until you have only your first one with the dts changes left (was 9c2fa44, IIRC)... or directly specify the ID.

The you need to --force push the branch again.

**Pull request closed without merging**
