### PR TITLE
Improve everything permissions

### PR DESCRIPTION
**Pull request by philcerf**
As per discussion in discord.

Perhaps you may want to have different option names, e.g. instead of `allow-everything-only` the name `allow-wildcard-only` or something like this could be a reasonable choice?

### CODE REVIEW

**Comment by jfberry** [comment]
This tidies these options up nicely.  In the new logging PR I have checks for valid options selected and a warn on startup. So I think that this would make sense to include these and would proposing queuing this until post logging changes merged.
This is also a good place to provide a backward compatibility setting - detecting the old settings and setting in memory the right setting and also providing a warning on startup that a deprecated config option has been used

**Comment by philcerf** [comment]
this now also fixes #327

**Comment by jfberry** [comment]
Now logging is patched you can see how to have poracle check for a valid entry in the config file and warn

**Comment by philcerf** [comment]
rebased and added the checking

**Comment by philcerf** [comment]
rebased and new option names

**Pull request merged**
