### PR TITLE
Remember messages to be deleted and event cache between restarts

### PR DESCRIPTION
**Pull request by jfberry**
Details of messages to be deleted and current webhook events will be stored in the .cache directory on shutdown. This will be reloaded on startup.

### CODE REVIEW

**Comment by hamster007Github** [comment]
Cleaning and avoiding duplicates after restart working fine on first test with Telegram 👌

**Comment by hamster007Github** [comment]
Running now for 2 days with telegram without any issues. No duplicates and cleaning messages correctly after restart.

**Comment by jfberry** [comment]
How many times have you restarted? Do you have any discord clean commands set up?

**Comment by hamster007Github** [comment]
Have groups and private chats with active cleaning (pokemon). Restarted 5...6 times with active tracked pokemon. But Telegram only.

**Pull request merged**
