### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by MadBlade91**
Psychic is "Psychokinese" in german, not just "Psycho" :)

Take a look here:
https://www.pokewiki.de/Psychokinese

### CODE REVIEW

**Comment by jfberry** [comment]
@ReuschelCGN ?

**Review by Fabio1988 — COMMENTED** [review]
Psychic is also the type, don't change it to the attack psychic... Two different things

**Comment by Fabio1988** [comment]
@MadBlade91 is the attack wrong in notifactions where the moves are listed?

**Comment by MadBlade91** [comment]
yea, the attacks are the issue
grafik

**Comment by Fabio1988** [comment]
It's right translated in the translations repo: https://github.com/WatWowMap/pogo-translations/blob/8a8bd432825f26ba4fdf759becd75d9f11a1cca1/static/locales/de.json#L3837

**Comment by MadBlade91** [comment]
how to fix the move section then?

**Comment by jfberry** [comment]
Poracle translates everything from English. This is a faulty design where words are re-used - I would happily accept a pull request to translate directly from keyword source

**Pull request closed without merging**
