### PR TITLE
Fix Egg & Raid message

### PR DESCRIPTION
**Pull request by nakratz**
## Description

Was getting an extra "" when receiving egg and raid reports. Upon further investigation discovered that the !egg and !raid commands were adding "" into the ping column. Noticed the !track command was not displaying this behavior. 

## Motivation and Context

Should fix future issues with the code as it followed past edits to !tracked

## How Has This Been Tested?

Local system tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by JimBim89** [comment]
I guess "lenght" was misspelled so it didn't behave correctly?

**Comment by nakratz** [comment]
I will investigate this further, I noticed the tracked command file had pings.length removed many commits ago. So to resolve the problem in raid and egg I removed it as well. Not sure what best path forward is.

**Comment by JimBim89** [comment]
Kartul mentioned this needs some testing with sqlite

**Comment by KartulUdus** [comment]
Sorted in 3d4a4a9

**Pull request closed without merging**
