### PR TITLE
Option to ignore raid hour eggs/raids

### PR DESCRIPTION
**Pull request by jfberry**
New option in general:
```
      "ignoreLongRaids": false                // ignore raids > 47m long to save raid hour spam
```

### CODE REVIEW

**Comment by plinytheelder** [comment]
worked like a charm.

**Comment by jfberry** [comment]
Super, I may change the config option naming slightly but will incorporate something along these lines very soon!

**Comment by plinytheelder** [comment]
for sure. Maybe change it to `ignoreEventRaids` since these things pop up every so often.

**Comment by jfberry** [comment]
or 'ignoreLongRaids' ... or... have it as a maximum value. Not quite sure what to do - but agree really helps keep down channel/bot spam

**Pull request merged**
