### PR TITLE
enableGymBattle missing from api config

### PR DESCRIPTION
**Pull request by jfberry**

### CODE REVIEW

**Comment by Ninjasoturi** [comment]
Thank you for the fast PR. Upon testing I noticed that the correct config variable is `fastify.config.tracking.enableGymBattle`. With that this works perfectly!

**Comment by jfberry** [comment]
> config.tracking.enableGymBattle

Shows my testing regime! Thanks, have pushed this change into the PR

**Comment by TurtIeSocks** [comment]
@jfberry can we get a patch bump?

**Comment by jfberry** [comment]
Version uplifted, this will be merged ahead of merge to master - so master will get 4.5.1

**Pull request merged**
